# Generated by Django 5.1.1 on 2024-09-25 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("producer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("AÇUCAR", "SUGGAR"),
                            ("MILHO", "CORN"),
                            ("ALGODÂO", "COTTON"),
                            ("CAFÉ", "COFFEE"),
                            ("CANA DE AÇUCAR", "SUGGAR CANE"),
                            ("SOJA", "SOY"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("total_area", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "agricultural_area",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "vegetation_area",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "planted_crops",
                    models.ManyToManyField(related_name="farms", to="farm.crop"),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producer_farm",
                        to="producer.producer",
                    ),
                ),
            ],
        ),
    ]
